<?php

namespace AppBundle\Repository;

/**
 * TransactionsTotalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionsTotalRepository extends \Doctrine\ORM\EntityRepository
{
}
