app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

restful_services:
    resource: "@AppBundle/Resources/config/routing_api.yml"
    type:     rest
    prefix:   /api

rest_services:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

js_routing:
    resource: "@AppBundle/Resources/config/routing_js.yml"