customer_rest:
    type: rest
    prefix: /v1
    resource: AppBundle\Controller\CustomerRestController
    name_prefix:  api_1_customer

transaction_rest:
    type: rest
    prefix: /v1
    resource: AppBundle\Controller\TransactionRestController
    name_prefix:  api_1_transaction